name: deploy from webhook
on:
  repository_dispatch:
    types: [webhook-deploy]
env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  # ※既存の pullreq_build / pushed_build は消す or 別の workflow に分けるとスッキリ
  webhook_build:
    name: Build(from webhook)
    runs-on: ubuntu-latest
    # webhook-deploy のときだけ動かす
    if: github.event_name == 'repository_dispatch' && github.event.action == 'webhook-deploy'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main   # ← ここは main / stage など、デプロイしたいブランチに合わせて
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://hasebe.g.kuroco.app/direct/menu/github/"
          webhook_secret: "6058cc0d39746b2a6781d4fc2e2c70fd"
          data: '{"single_zip":"0","domain":"hasebe.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
